name: UI Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Install Firefox for Selenium
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      # Install Geckodriver
      - name: Install Geckodriver
        uses: browser-actions/setup-geckodriver@v1

      # Build and test
      - name: Run Gradle tests
        run: ./gradlew test
